name: coutinho
favicon: null
layout_spectrum: 0.26165
typography_spectrum: 0.23755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4f4f4f'
    - '#7f7f7f'
    - '#afafaf'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
