name: coutinho
favicon: null
layout_spectrum: 0.83914
typography_spectrum: 0.75446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a9ab6'
    - '#dfe7ec'
    - '#bfc9d0'
    - '#32404c'
    - '#6c6f70'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
